# Generated by Django 2.1.5 on 2019-12-11 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
