# Generated by Django 2.1.5 on 2019-12-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_opportunity_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='vol_name',
            field=models.CharField(max_length=50),
        ),
    ]
